//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using Assets.Alleles;
using System.Collections.Generic;

public class NutrientValueAllele : Allele
{
	private Dictionary<Nutrient, int> priorities;

	void Awake() {
		priorities = new Dictionary<Nutrient, int>();
	}

	public void registerNutrientDesire(Nutrient n, int desire) {
		if (!priorities.ContainsKey(n)) {
			priorities[n] = 0;
		}
		priorities[n] += desire;
	}

	public int getNutrientPriority(Nutrient n) {
		return priorities.ContainsKey(n) ? priorities[n] : 0;
	}

	public float getNutrientProbability(Nutrient n) {
		float sum = 0;
		foreach (int val in priorities.Values) {
			sum += val;
		}

		return ((float) getNutrientPriority(n)) / sum;
	}
}

