//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Assets;
using Assets.Alleles;

public class PlantStuffAllele : Allele
{

	void Start() {
		Tile t = TileManager.instance.getTileClosestTo(transform.position);
		t.Plant = gameObject;
		this.transform.position = t.transform.position;
	}
}

